import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "./provider";

export const metadata: Metadata = {
   title: "Paytm-Clone",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <Provider>
            <body className=" bg-amber-700/5">{children}</body>
         </Provider>
      </html>
   );
}
